### ISSUE TITLE
doesnt load

### ISSUE THREAD

**Issue by dropalways** [face-hh/griddycode#2]
just shows a grey screen
![Bussin_GriddyCode_Rwa5bou83a](https://github.com/face-hh/griddycode/assets/120043514/3e235143-8ca5-477d-af09-9ba9b26ce4ae)

**Comment by 7valkio** [comment]
If you press the ESC key, it shows the first line but when you type, nothing shows or sometimes shows and sometimes just inputs blanks.

**Comment by 7valkio** [comment]
It seems to open with the first line visible and music playing now but then slowly zooms more into itself and has a strange white highlight over the whole first line.

https://github.com/face-hh/griddycode/assets/113270877/1cbea18f-b7cd-4c55-9ba2-d3b92b1d3c71

**Comment by face-hh** [comment]
The white highlighting is intentional but it slowly zooming into itself isn't, and I can't seem to replicate it on Linux.

![image](https://github.com/face-hh/griddycode/assets/69168154/fdc97d4a-bd3e-4d49-8317-86c592e9f5e3)

**Comment by face-hh** [comment]
> It seems to open with the first line visible and music playing now but then slowly zooms more into itself and has a strange white highlight over the whole first line.
> 
>  Recording.2024-03-19.144122.mp4

In your recording the background is black which means it failed to load the themes. I'll download the dev build on my Windows machine to test it out

**Comment by dropalways** [comment]
> It seems to open with the first line visible and music playing now but then slowly zooms more into itself and has a strange white highlight over the whole first line.
> Recording.2024-03-19.144122.mp4

yeah same thing happens to me

**Comment by face-hh** [comment]
So after testing on Windows, the release build seems to have this issue, but running the project from within the Godot Editor doesn't. I will try to export the project with different settings to see how it will react.

For the record, the Linux build works just fine.

**Comment by GearKite** [comment]
I have the same issue as @7valkio on Arch Linux (btw), there are many errors in the console, which might be related:

<details>

<summary>Logs</summary>

```
ERROR: Can't open dynamic library: addons/luaAPI/bin/libluaapi.linux.template_debug.x86_64.so. Error: /home/ice/Downloads/../lib/libluaapi.linux.template_debug.x86_64.so: cannot open shared object file: No such file or directory.
   at: open_dynamic_library (drivers/unix/os_unix.cpp:660)
ERROR: GDExtension dynamic library not found: addons/luaAPI/bin/libluaapi.linux.template_debug.x86_64.so
   at: open_library (core/extension/gdextension.cpp:719)
ERROR: Failed loading resource: res://addons/luaAPI/luaAPI.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
   at: _load (core/io/resource_loader.cpp:274)
ERROR: Error loading extension: res://addons/luaAPI/luaAPI.gdextension
   at: load_extensions (core/extension/gdextension_manager.cpp:234)
Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.277 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3090
 
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
ERROR: Failed to load script "res://Scripts/lua_singleton.gd" with error "Parse error".
   at: load (modules/gdscript/gdscript.cpp:2788)
ERROR: Failed to instantiate an autoload, script 'res://Scripts/lua_singleton.gd' does not inherit from 'Node'.
   at: start (main/main.cpp:3207)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://Scripts/file_manager.gd:-1)
ERROR: Failed to load script "res://Scripts/file_manager.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not resolve member "lua".
          at: GDScript::reload (res://Scripts/settings.gd:71)
ERROR: Failed to load script "res://Scripts/settings.gd" with error "Parse error".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://Scripts/file_dialog.gd:-1)
ERROR: Failed to load script "res://Scripts/file_dialog.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://Scripts/settings_list.gd:-1)
ERROR: Failed to load script "res://Scripts/settings_list.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://Scripts/theme_chooser.gd:-1)
ERROR: Failed to load script "res://Scripts/theme_chooser.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://Scripts/comment.gd:-1)
ERROR: Failed to load script "res://Scripts/comment.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://Scripts/comments.gd:-1)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:281)
SCRIPT ERROR: Parse Error: Could not find type "LuaAPI" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Identifier "LuaAPI" not declared in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:282)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:340)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:341)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:353)
SCRIPT ERROR: Parse Error: Could not find type "LuaError" in the current scope.
          at: GDScript::reload (res://Scripts/lua_singleton.gd:354)
SCRIPT ERROR: Compile Error: 
          at: GDScript::reload (res://Scripts/comments_overlay.gd:-1)
ERROR: Failed to load script "res://Scripts/comments_overlay.gd" with error "Compilation failed".
   at: load (modules/gdscript/gdscript.cpp:2788)
SCRIPT ERROR: Invalid get index 'on_theme_load' (on base: 'Nil').
          at: _ready (res://Scripts/settings_list.gd:7)
SCRIPT ERROR: Invalid get index 'on_theme_load' (on base: 'Nil').
          at: _ready (res://Scripts/theme_chooser.gd:9)
SCRIPT ERROR: Invalid get index 'done_parsing' (on base: 'Nil').
          at: Comments._ready (res://Scripts/comments.gd:8)
SCRIPT ERROR: Invalid get index 'gui' (on base: 'Nil').
          at: CommentsOverlay._ready (res://Scripts/comments_overlay.gd:9)
SCRIPT ERROR: Cannot call method 'get_files' on a null value.
          at: FileManager.inject_lua (res://Scripts/file_manager.gd:43)
SCRIPT ERROR: Invalid set index 'themes' (on base: 'Nil') with value of type 'Array'.
          at: FileManager._ready (res://Scripts/file_manager.gd:17)
SCRIPT ERROR: Invalid call. Nonexistent function 'get_longest_line' in base 'CodeEdit'.
          at: Camera._process (res://Scripts/camera.gd:35)
ERROR: Tween (bound to /root/Editor/Misc/Cam): started with no Tweeners.
   at: step (scene/animation/tween.cpp:319)
SCRIPT ERROR: Invalid call. Nonexistent function 'get_longest_line' in base 'CodeEdit'.
          at: Camera._process (res://Scripts/camera.gd:35)
ERROR: Tween (bound to /root/Editor/Misc/Cam): started with no Tweeners.
   at: step (scene/animation/tween.cpp:319)
SCRIPT ERROR: Invalid call. Nonexistent function 'get_longest_line' in base 'CodeEdit'.
          at: Camera._process (res://Scripts/camera.gd:35)
```

</details>

**Comment by afoxfan** [comment]
still have the issue after the updated build.

**Comment by afoxfan** [comment]
i downloaded the older version and now the "1" after pressing escape is high quality

**Comment by face-hh** [comment]
> i downloaded the older version and now the "1" after pressing escape is high quality

The blurriness and unicode issue can be fixed by installing [Nerd Fonts](https://www.nerdfonts.com/)

**Comment by face-hh** [comment]
> I have the same issue as @7valkio on Arch Linux (btw), there are many errors in the console, which might be related:
> 
> Logs

This should be fixed in the latest Linux release, a library was missing!

**Comment by 7valkio** [comment]
> The blurriness and unicode issue can be fixed by insta

Which of the Nord Fonts would I need to install?

**Comment by Blackneeed** [comment]
I have a issue, that only some of the characters appear, and most of them are blurry.
Also which one of the Nerd Fonts should i install?

**Comment by face-hh** [comment]
https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.zip - this seems to be it

**Comment by Blackneeed** [comment]
Thanks, will see if it works

**Comment by Blackneeed** [comment]
![image](https://github.com/face-hh/griddycode/assets/121721929/3916c4ed-20d6-4edb-bc07-1b4c16e8c20b)
This is how '#include <stdio.h>' looks.

**Comment by Blackneeed** [comment]
After downloading all of the font styles of the Fira Mono Nerd Font

**Comment by face-hh** [comment]
> ![image](https://private-user-images.githubusercontent.com/121721929/314131743-3916c4ed-20d6-4edb-bc07-1b4c16e8c20b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NjM2NzYsIm5iZiI6MTcxMDg2MzM3NiwicGF0aCI6Ii8xMjE3MjE5MjkvMzE0MTMxNzQzLTM5MTZjNGVkLTIwZDYtNGVkYi1iYzA3LTFiNGMxNmU4YzIwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOVQxNTQ5MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjA0ZjdiNjk2ODE1MjRiOTdiNWM4NTk5NTI3MTE1OWE5M2I2YjcwYTg0YmY3NDE1YWJhZTI3OGZkYWViY2FmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6YWTiJXmxdfv8xPQ5joxsZIqyE0itVaqxuFuo776oSA) This is how '#include <stdio.h>' looks.

Seems like the extension isn't supported so preset keywords default to being the same color as the background (black). Assuming you're using a C-related language, GriddyCode will try to locate "c.lua" in "langs" - which doesn't exist.

The only supported file extension at the moment is `.js` (JavaScript)

**Comment by Blackneeed** [comment]
When writing only letters, it is also blank

**Comment by Blackneeed** [comment]
Also i am not opening a file, i run it with no args

**Comment by face-hh** [comment]
Then that's probably it, press CTRL + O and choose a file. It shouldn't be possible to use the editor without opening a file, I made it possible while testing and forgot to switch it back...

**Comment by Blackneeed** [comment]
Also, you should probaly add support for .txt

**Comment by 7valkio** [comment]
> When writing only letters, it is also blank

Yeah, I get the same even after installing the fonts. Although, after pressing ESC it shows the line but all blurry

https://github.com/face-hh/griddycode/assets/113270877/c2bf90e5-5a49-4ef8-aeb7-2058daed0cda

**Comment by Blackneeed** [comment]
idk why, but i feel like a lot of users might need itr

**Comment by Blackneeed** [comment]
Z:\GriddyCode>"Bussin GriddyCode.exe" test.js

Z:\GriddyCode>Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org
Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3090

SCRIPT ERROR: Cannot call method 'get_files' on a null value.
          at: FileManager.inject_lua (res://Scripts/file_manager.gd:43)
ERROR 6: error while opening file 'user://langs/.lua'
ERROR 6: error while opening file 'user://themes/One Dark Pro Darker.lua'

Why?

**Comment by face-hh** [comment]
> > When writing only letters, it is also blank
> 
> Yeah, I get the same even after installing the fonts. Although, after pressing ESC it shows the line but all blurry
> 
>  Recording.2024-03-19.155611.mp4

Weird, when you press ESC you're exiting the initial "Welcome" screen that forces you to choose a file.

But for why the welcome screen is invisible, I have no clue 🙃

**Comment by Blackneeed** [comment]
Also, i think it is a issue with font rendering cause even before pressing ESC, i cannot write anything

**Comment by face-hh** [comment]
> Z:\GriddyCode>"Bussin GriddyCode.exe" test.js
> 
> Z:\GriddyCode>Godot Engine v4.2.1.stable.official.b09f793f5 - https://godotengine.org Vulkan API 1.3.242 - Forward+ - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 3090
> 
> SCRIPT ERROR: Cannot call method 'get_files' on a null value. at: FileManager.inject_lua (res://Scripts/file_manager.gd:43) ERROR 6: error while opening file 'user://langs/.lua' ERROR 6: error while opening file 'user://themes/One Dark Pro Darker.lua'
> 
> Why?

Might be a Windows issue (which for some reason my version of Windows ignored)

In the code, the initial folder that is being opened is "/" (root for Linux), that might explain the invisible welcome screen. I will try to fix that right now & publish a new release.

**Comment by face-hh** [comment]
The invisible file picker should be fixed in the latest Windows release

**Comment by ThatFrogDev** [comment]
@face-hh it still doesnt work... only numbers work, no text. the welcome screen doesnt show up as well.

**Comment by 7valkio** [comment]
I feel like Griddycode is completely cooked on Windows 11. The first time you open is the only time you will hear the music, after that, it will not play any music.

https://github.com/face-hh/griddycode/assets/113270877/0fc34fd1-8037-49da-bd9a-8918423af396

**Comment by HumanGamer** [comment]
No text rendering here, and music only worked on first launch. I installed the Fira Code fonts linked above. I'm on Windows 10 x64, RTX 3090ti, Ryzen 9 5950X, 48 GB Ram.

**Comment by face-hh** [comment]
Everything should now properly work on the v1.0.3 release.

To fix the blurriness, install [Nerdfont](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.zip)

Thanks to everyone who helped <3
